[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python ner_project/manage.py migrate && python ner_project/manage.py collectstatic --noinput && cd ner_project && gunicorn ner_project.wsgi --bind 0.0.0.0:$PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
