[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd ner_project && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn ner_project.wsgi"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
